# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.box = "puppetlabs/ubuntu-14.04-64-puppet"
    config.vm.network "private_network", ip: "192.168.33.10"
    #config.vm.hostname = "scotchbox"
    config.vm.synced_folder "../.", "/var/www/selfblog", :nfs => { :mount_options => ["dmode=777","fmode=666"] }

    config.vm.provision "fix-no-tty", type: "shell" do |s|
        s.privileged = false
        s.inline = "sudo sed -i '/tty/!s/mesg n/tty -s \\&\\& mesg n/' /root/.profile"
    end

    config.vm.provision :puppet do |puppet|
        puppet.facter = {
            "vagrant" => "1",
            "server" => "selfblog",
         #   "environment"   => "development",
        }
     #   puppet.hiera_config_path = "puppet/hiera.yaml"
        puppet.environment_path     = "puppet/environments"
        puppet.environment          = "develop"
        puppet.options = "--verbose --debug"
    end

    config.vm.provision "bootstrap", type:"shell", run: "always", path: "bootstrap/bootstrap.sh"
    config.vm.provision "frontend", type:"shell", run: "always", path: "bootstrap/frontend.sh"

    config.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 2
    end

end