<?php

namespace AppBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByTag($tagName){
        return $this->createQueryBuilder('post')
            ->select('post, tag')
            ->leftJoin('post.tags', 'tag')
            ->andWhere('tag.name = :name')
            ->setParameter('name', $tagName)
            ->orderBy('post.createdAt', 'DESC')
            ->getQuery()
            ->getResult()
            ;
    }

    public function findByWord($word){
        return $this->createQueryBuilder('post')
            ->select('post, tag')
            ->leftJoin('post.tags', 'tag')
            ->where('post.title LIKE :word')
            ->orWhere('post.content LIKE :word')
            ->setParameter('word', '%' . $word . '%')
            ->orderBy('post.createdAt', 'DESC')
            ->getQuery()
            ->getResult()
            ;
    }
}
