<?php

namespace AppBundle\Repository;
use Doctrine\ORM\Query;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends \Doctrine\ORM\EntityRepository
{
    public function getKeyPairs()
    {
        $allTags = $this->getAllAsArray();
        $keyPairsArray = [];
        foreach ($allTags as $tag) {
            $keyPairsArray[$tag['name']] = $tag['id'];
        }
        return $keyPairsArray;

    }

    public function getAllAsArray()
    {
        return $this->createQueryBuilder('tag')
            ->select('tag')
            ->getQuery()
            ->getArrayResult()
            ;
    }
}
