# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12



    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory:
                users:
                   admin:
                      password: $2y$12$F50g4VwBRRrdpsg2A0hNI.LQ3NcxbShwZrJ06P2cGKbY5Kk61Gkw.
                      roles: 'ROLE_ADMIN'

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            provider: in_memory
            form_login:
              login_path: login
              check_path: login
              username_parameter: "login[username]"
              password_parameter: "login[password]"
            logout:
              path:   logout
              target: homepage

    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/admin, roles: ROLE_ADMIN }
